package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/yhaliwaizman/capture/internal/detector"
	"github.com/yhaliwaizman/capture/internal/walker"
)

type templateConfig struct {
	Root   string
	Output string
	Ignore []string
}

var tmplConfig templateConfig

var templateCmd = &cobra.Command{
	Use:   "template",
	Short: "Generate .env template from source usage",
	Long: `Template scans source files for environment variable usage
and generates a grouped .env template file.`,
	Example: `  capture template --root . --output .env.example
  capture template --root ./services/api --output ./services/api/.env.example --ignore vendor,tmp`,
	SilenceUsage:  true,
	SilenceErrors: true,
	RunE:          runTemplate,
}

func init() {
	templateCmd.Flags().StringVar(&tmplConfig.Root, "root", ".", "Root directory to scan")
	templateCmd.Flags().StringVar(&tmplConfig.Output, "output", ".env.example", "Output path for generated template")
	templateCmd.Flags().StringSliceVar(&tmplConfig.Ignore, "ignore", []string{}, "Comma-separated list of directories to ignore")
}

func runTemplate(cmd *cobra.Command, args []string) error {
	if info, err := os.Stat(tmplConfig.Root); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "Error: directory does not exist: %s\n", tmplConfig.Root)
		return NewExitError(err, 2)
	} else if err != nil {
		fmt.Fprintf(os.Stderr, "Error: cannot access directory: %v\n", err)
		return NewExitError(err, 2)
	} else if !info.IsDir() {
		fmt.Fprintf(os.Stderr, "Error: path is not a directory: %s\n", tmplConfig.Root)
		return NewExitError(fmt.Errorf("not a directory"), 2)
	}

	for i := range tmplConfig.Ignore {
		tmplConfig.Ignore[i] = strings.TrimSpace(tmplConfig.Ignore[i])
	}

	vars, err := detectUsedEnvVars(tmplConfig.Root, tmplConfig.Ignore)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: failed to scan files: %v\n", err)
		return NewExitError(err, 2)
	}

	content := buildEnvTemplate(vars)
	outputDir := filepath.Dir(tmplConfig.Output)
	if outputDir != "" && outputDir != "." {
		if err := os.MkdirAll(outputDir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: failed to create output directory: %v\n", err)
			return NewExitError(err, 2)
		}
	}
	if err := os.WriteFile(tmplConfig.Output, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error: failed to write template file: %v\n", err)
		return NewExitError(err, 2)
	}

	fmt.Fprintf(os.Stdout, "Generated %s with %d variable(s)\n", tmplConfig.Output, len(vars))
	return nil
}

func detectUsedEnvVars(root string, ignore []string) ([]string, error) {
	fileWalker := walker.NewFileWalker()
	detectorFactory := detector.NewDetectorFactory()

	files, err := fileWalker.Walk(root, ignore)
	if err != nil {
		return nil, err
	}

	used := make(map[string]bool)
	for _, filePath := range files {
		d := detectorFactory.Create(filepath.Ext(filePath))
		if d == nil {
			continue
		}
		locations, detectErr := d.Detect(filePath)
		if detectErr != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to process file %s: %v\n", filePath, detectErr)
			continue
		}
		for varName := range locations {
			used[varName] = true
		}
	}

	vars := make([]string, 0, len(used))
	for varName := range used {
		vars = append(vars, varName)
	}
	sort.Strings(vars)
	return vars, nil
}

func buildEnvTemplate(vars []string) string {
	var builder strings.Builder
	builder.WriteString("# Generated by capture on ")
	builder.WriteString(time.Now().Format("2006-01-02"))
	builder.WriteByte('\n')
	builder.WriteString("# Copy this file to .env and fill in the values\n\n")

	if len(vars) == 0 {
		builder.WriteString("# No environment variables detected.\n")
		return builder.String()
	}

	grouped := make(map[string][]string)
	for _, varName := range vars {
		group := templateGroup(varName)
		grouped[group] = append(grouped[group], varName)
	}

	for _, group := range orderedTemplateGroups(grouped) {
		sort.Strings(grouped[group])
		builder.WriteString("# ")
		builder.WriteString(templateGroupTitle(group))
		builder.WriteByte('\n')
		for _, varName := range grouped[group] {
			builder.WriteString(varName)
			builder.WriteString("=\n")
		}
		builder.WriteByte('\n')
	}

	return builder.String()
}

func templateGroup(varName string) string {
	if idx := strings.Index(varName, "_"); idx > 0 {
		return varName[:idx]
	}
	return "GENERAL"
}

func orderedTemplateGroups(groups map[string][]string) []string {
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	if len(keys) == 0 || keys[0] == "GENERAL" {
		return keys
	}
	for i, k := range keys {
		if k == "GENERAL" {
			return append([]string{"GENERAL"}, append(keys[:i], keys[i+1:]...)...)
		}
	}
	return keys
}

func templateGroupTitle(group string) string {
	if group == "GENERAL" {
		return "General variables"
	}
	return group + " variables"
}
